export const testDatasetExact = [
  // birth_date
  { text: "when were you born", expectedIntent: "birth_date" },
  { text: "what year were you born", expectedIntent: "birth_date" },
  { text: "when did your life begin", expectedIntent: "birth_date" },
  { text: "what is your birth year", expectedIntent: "birth_date" },
  { text: "tell me when you were born", expectedIntent: "birth_date" },
  { text: "when did you first come into the world", expectedIntent: "birth_date" },
  { text: "when did you first come into the world", expectedIntent: "birth_date" },
  { text: "when exactly were you born", expectedIntent: "birth_date" },
  { text: "what is your date of birth", expectedIntent: "birth_date" },
  { text: "in what year were you born", expectedIntent: "birth_date" },

  // birthplace
  { text: "where were you born", expectedIntent: "birthplace" },
  { text: "what land were you born in", expectedIntent: "birthplace" },
  { text: "where did your life begin", expectedIntent: "birthplace" },
  { text: "where did you come from", expectedIntent: "birthplace" },
  { text: "what is your birthplace", expectedIntent: "birthplace" },
  { text: "where did you enter the world", expectedIntent: "birthplace" },
  { text: "tell me where you were born", expectedIntent: "birthplace" },
  { text: "what part of egypt were you born in", expectedIntent: "birthplace" },
  { text: "where exactly were you born", expectedIntent: "birthplace" },
  { text: "in what region were you born", expectedIntent: "birthplace" },

  // childhood_environment
  { text: "what was your childhood environment like", expectedIntent: "childhood_environment" },
  { text: "where did you grow up", expectedIntent: "childhood_environment" },
  { text: "what was life like when you were a child", expectedIntent: "childhood_environment" },
  { text: "describe your early environment", expectedIntent: "childhood_environment" },
  { text: "what surroundings did you have as a child", expectedIntent: "childhood_environment" },
  { text: "how did you grow up", expectedIntent: "childhood_environment" },
  { text: "where did you live as a child", expectedIntent: "childhood_environment" },
  { text: "what was the palace like when you were young", expectedIntent: "childhood_environment" },
  { text: "tell me about your early environment", expectedIntent: "childhood_environment" },
  { text: "what was your childhood setting like", expectedIntent: "childhood_environment" },

  // childhood_upbringing
  { text: "how were you raised", expectedIntent: "childhood_upbringing" },
  { text: "what was your upbringing like", expectedIntent: "childhood_upbringing" },
  { text: "how did your childhood shape you", expectedIntent: "childhood_upbringing" },
  { text: "what training did you receive as a child", expectedIntent: "childhood_upbringing" },
  { text: "what was expected of you growing up", expectedIntent: "childhood_upbringing" },
  { text: "describe your upbringing", expectedIntent: "childhood_upbringing" },
  { text: "what did you learn as a child", expectedIntent: "childhood_upbringing" },
  { text: "were you trained for leadership", expectedIntent: "childhood_upbringing" },
  { text: "how were princes raised in egypt", expectedIntent: "childhood_upbringing" },
  { text: "tell me about your upbringing", expectedIntent: "childhood_upbringing" },

  // titles
  { text: "what titles did you hold", expectedIntent: "titles" },
  { text: "what were you called", expectedIntent: "titles" },
  { text: "what royal titles did you have", expectedIntent: "titles" },
  { text: "what was your official title", expectedIntent: "titles" },
  { text: "list your titles", expectedIntent: "titles" },
  { text: "what did they call you as ruler", expectedIntent: "titles" },
  { text: "what names showed your status", expectedIntent: "titles" },
  { text: "what did egypt call you", expectedIntent: "titles" },
  { text: "tell me your titles", expectedIntent: "titles" },
  { text: "what were your royal titles", expectedIntent: "titles" },

  // names_epithets
  { text: "what names did you use", expectedIntent: "names_epithets" },
  { text: "what were your other names", expectedIntent: "names_epithets" },
  { text: "what epithets did you have", expectedIntent: "names_epithets" },
  { text: "what was your throne name", expectedIntent: "names_epithets" },
  { text: "what were you also called", expectedIntent: "names_epithets" },
  { text: "what meaning did your names have", expectedIntent: "names_epithets" },
  { text: "tell me your full name", expectedIntent: "names_epithets" },
  { text: "what did priests call you", expectedIntent: "names_epithets" },
  { text: "what titles or names identified your divinity", expectedIntent: "names_epithets" },
  { text: "what are your royal names", expectedIntent: "names_epithets" },

  // personality_traits
  { text: "what were you like", expectedIntent: "personality_traits" },
  { text: "how would you describe your personality", expectedIntent: "personality_traits" },
  { text: "what kind of ruler were you", expectedIntent: "personality_traits" },
  { text: "were you confident", expectedIntent: "personality_traits" },
  { text: "were you strict or kind", expectedIntent: "personality_traits" },
  { text: "how did you behave as pharaoh", expectedIntent: "personality_traits" },
  { text: "describe your character", expectedIntent: "personality_traits" },
  { text: "what traits defined you", expectedIntent: "personality_traits" },
  { text: "what type of leader were you", expectedIntent: "personality_traits" },
  { text: "what was your personality", expectedIntent: "personality_traits" },

  // age_at_accession
  { text: "how old were you when you became pharaoh", expectedIntent: "age_at_accession" },
  { text: "what age did you take the throne", expectedIntent: "age_at_accession" },
  { text: "how old were you when you began ruling", expectedIntent: "age_at_accession" },
  { text: "when did you first rule egypt", expectedIntent: "age_at_accession" },
  { text: "what age were you when crowned", expectedIntent: "age_at_accession" },
  { text: "how young were you when you took power", expectedIntent: "age_at_accession" },
  { text: "when did you start ruling", expectedIntent: "age_at_accession" },
  { text: "at what age did you become ruler", expectedIntent: "age_at_accession" },
  { text: "how old were you at your coronation", "expectedIntent": "age_at_accession" },
  { text: "what was your age when you ascended", "expectedIntent": "age_at_accession" },

  // length_of_reign
  { text: "how long did you rule", expectedIntent: "length_of_reign" },
  { text: "how long were you pharaoh", expectedIntent: "length_of_reign" },
  { text: "what was the length of your reign", expectedIntent: "length_of_reign" },
  { text: "how many years did you rule", expectedIntent: "length_of_reign" },
  { text: "how long did your reign last", expectedIntent: "length_of_reign" },
  { text: "how long were you in power", expectedIntent: "length_of_reign" },
  { text: "how long did you lead egypt", expectedIntent: "length_of_reign" },
  { text: "how many years did you serve as pharaoh", expectedIntent: "length_of_reign" },
  { text: "what was the duration of your reign", expectedIntent: "length_of_reign" },
  { text: "for how many years were you king", expectedIntent: "length_of_reign" },

  // daily_routine
  { text: "what was your daily routine", expectedIntent: "daily_routine" },
  { text: "how did you spend your day", expectedIntent: "daily_routine" },
  { text: "what did you do each day", expectedIntent: "daily_routine" },
  { text: "describe your daily schedule", expectedIntent: "daily_routine" },
  { text: "how did your day normally go", expectedIntent: "daily_routine" },
  { text: "what did a day look like for you", expectedIntent: "daily_routine" },
  { text: "what did you do most days", expectedIntent: "daily_routine" },
  { text: "how did pharaohs spend their day", expectedIntent: "daily_routine" },
  { text: "tell me about your daily routine", expectedIntent: "daily_routine" },
  { text: "what was a typical day for you", expectedIntent: "daily_routine" }
];

export const testDatasetFuzzy = [
  { text: "wen were you born", expectedIntent: "birth_date" },
  { text: "whats your birth year", expectedIntent: "birth_date" },
  { text: "wat year u born", expectedIntent: "birth_date" },
  { text: "when u come into world", expectedIntent: "birth_date" },
  { text: "tell me ur birth year", expectedIntent: "birth_date" },
  { text: "when did u first see the world", expectedIntent: "birth_date" },
  { text: "what yr were u born", expectedIntent: "birth_date" },
  { text: "wen did your life start", expectedIntent: "birth_date" },
  { text: "whats ur birthday year", expectedIntent: "birth_date" },
  { text: "when exactly u born", expectedIntent: "birth_date" },

  { text: "were you born in the delta", expectedIntent: "birthplace" },
  { text: "where u from", expectedIntent: "birthplace" },
  { text: "wat land u born in", expectedIntent: "birthplace" },
  { text: "were did u come from", expectedIntent: "birthplace" },
  { text: "whats your birthplace", expectedIntent: "birthplace" },
  { text: "tell me were u were born", expectedIntent: "birthplace" },
  { text: "wat part of egypt u born", expectedIntent: "birthplace" },
  { text: "were exactly u born", expectedIntent: "birthplace" },
  { text: "in wat region u born", expectedIntent: "birthplace" },
  { text: "which place u born at", expectedIntent: "birthplace" },

  { text: "what was your young life like", expectedIntent: "childhood_environment" },
  { text: "were did u grow up", expectedIntent: "childhood_environment" },
  { text: "wat was life like wen u were a kid", expectedIntent: "childhood_environment" },
  { text: "describe ur early environment", expectedIntent: "childhood_environment" },
  { text: "wat surroundings u had as a kid", expectedIntent: "childhood_environment" },
  { text: "how u grow up", expectedIntent: "childhood_environment" },
  { text: "were u live as a child", expectedIntent: "childhood_environment" },
  { text: "wat was palace like wen young", expectedIntent: "childhood_environment" },
  { text: "tell me bout ur early life", expectedIntent: "childhood_environment" },
  { text: "wat was ur childhood like", expectedIntent: "childhood_environment" },

  { text: "how did you learn as a child", expectedIntent: "childhood_upbringing" },
  { text: "how u raised", expectedIntent: "childhood_upbringing" },
  { text: "wat was ur upbringing", expectedIntent: "childhood_upbringing" },
  { text: "how childhood shape u", expectedIntent: "childhood_upbringing" },
  { text: "wat training u got as kid", expectedIntent: "childhood_upbringing" },
  { text: "wat was expected of u growing up", expectedIntent: "childhood_upbringing" },
  { text: "describe ur upbringing", expectedIntent: "childhood_upbringing" },
  { text: "wat u learn as a child", expectedIntent: "childhood_upbringing" },
  { text: "were u trained 4 leadership", expectedIntent: "childhood_upbringing" },
  { text: "how princes raised back then", expectedIntent: "childhood_upbringing" },

  { text: "what were your titles", expectedIntent: "titles" },
  { text: "wat titles u had", expectedIntent: "titles" },
  { text: "wat they call u", expectedIntent: "titles" },
  { text: "wat royal titles u have", expectedIntent: "titles" },
  { text: "wat was ur official title", expectedIntent: "titles" },
  { text: "list ur titles", expectedIntent: "titles" },
  { text: "wat they call u as ruler", expectedIntent: "titles" },
  { text: "wat names showed ur status", expectedIntent: "titles" },
  { text: "wat egypt call u", expectedIntent: "titles" },
  { text: "tell me ur titles", expectedIntent: "titles" },

  { text: "did you have other names", expectedIntent: "names_epithets" },
  { text: "wat names u use", expectedIntent: "names_epithets" },
  { text: "wat were ur other names", expectedIntent: "names_epithets" },
  { text: "wat epithets u had", expectedIntent: "names_epithets" },
  { text: "wat was ur throne name", expectedIntent: "names_epithets" },
  { text: "wat u also called", expectedIntent: "names_epithets" },
  { text: "wat meaning ur names have", expectedIntent: "names_epithets" },
  { text: "tell me ur full name", expectedIntent: "names_epithets" },
  { text: "wat priests call u", expectedIntent: "names_epithets" },
  { text: "wat are ur royal names", expectedIntent: "names_epithets" },

  { text: "wat were u like", expectedIntent: "personality_traits" },
  { text: "how u describe ur personality", expectedIntent: "personality_traits" },
  { text: "wat kind of ruler u were", expectedIntent: "personality_traits" },
  { text: "were u confident", expectedIntent: "personality_traits" },
  { text: "were u strict or nice", expectedIntent: "personality_traits" },
  { text: "how u behave as pharaoh", expectedIntent: "personality_traits" },
  { text: "describe ur character", expectedIntent: "personality_traits" },
  { text: "wat traits defined u", expectedIntent: "personality_traits" },
  { text: "wat type leader u were", expectedIntent: "personality_traits" },
  { text: "wat was ur personality like", expectedIntent: "personality_traits" },

  { text: "how young were you when you took the throne", expectedIntent: "age_at_accession" },
  { text: "how old u when became pharaoh", expectedIntent: "age_at_accession" },
  { text: "wat age u take throne", expectedIntent: "age_at_accession" },
  { text: "how old u wen began ruling", expectedIntent: "age_at_accession" },
  { text: "wen u first rule egypt", expectedIntent: "age_at_accession" },
  { text: "wat age u wen crowned", expectedIntent: "age_at_accession" },
  { text: "how young u wen took power", expectedIntent: "age_at_accession" },
  { text: "wen u start ruling", expectedIntent: "age_at_accession" },
  { text: "at wat age u become ruler", expectedIntent: "age_at_accession" },
  { text: "how old at coronation", expectedIntent: "age_at_accession" },

  { text: "how long u rule", expectedIntent: "length_of_reign" },
  { text: "how long u pharaoh", expectedIntent: "length_of_reign" },
  { text: "wat was length of ur reign", expectedIntent: "length_of_reign" },
  { text: "how many years u rule", expectedIntent: "length_of_reign" },
  { text: "how long ur reign last", expectedIntent: "length_of_reign" },
  { text: "how long u in power", expectedIntent: "length_of_reign" },
  { text: "how long u lead egypt", expectedIntent: "length_of_reign" },
  { text: "how many yrs u serve as pharaoh", expectedIntent: "length_of_reign" },
  { text: "wat was duration of ur reign", expectedIntent: "length_of_reign" },
  { text: "for how many years u king", expectedIntent: "length_of_reign" },

  { text: "what was your routine", expectedIntent: "daily_routine" },
  { text: "wat was ur daily routine", expectedIntent: "daily_routine" },
  { text: "how u spend ur day", expectedIntent: "daily_routine" },
  { text: "wat u do each day", expectedIntent: "daily_routine" },
  { text: "describe ur daily schedule", expectedIntent: "daily_routine" },
  { text: "how ur day normally go", expectedIntent: "daily_routine" },
  { text: "wat a day look like 4 u", expectedIntent: "daily_routine" },
  { text: "wat u do most days", expectedIntent: "daily_routine" },
  { text: "how pharaohs spend their day", expectedIntent: "daily_routine" },
  { text: "tell me bout ur daily routine", expectedIntent: "daily_routine" }
];

export const testDatasetBoundary = [
  // birth_date (only direct references map)
  { text: "when did you come into the world", expectedIntent: "birth_date" },
  { text: "what era were you born in", expectedIntent: "birth_date" },
  { text: "how old are you now", expectedIntent: null },
  { text: "what century were you from", expectedIntent: null },
  { text: "when was ramses ii alive", expectedIntent: null },
  { text: "what dynasty were you born into", expectedIntent: null },
  { text: "tell me about your birth", expectedIntent: "birth_date" },
  { text: "when did you arrive", expectedIntent: "birth_date" },
  { text: "what time period are you from", expectedIntent: null },
  { text: "how long ago did you live", expectedIntent: null },

  // birthplace (geographic origin only)
  { text: "what land were you born in", expectedIntent: "birthplace" },
  { text: "which city is your home", expectedIntent: null },
  { text: "what region are you from", expectedIntent: "birthplace" },
  { text: "where is your palace", expectedIntent: null },
  { text: "what part of the world are you from", expectedIntent: "birthplace" },
  { text: "did you live in thebes", expectedIntent: null },
  { text: "where is your kingdom", expectedIntent: null },
  { text: "what country are you from", expectedIntent: "birthplace" },
  { text: "where did your family live", expectedIntent: null },
  { text: "what city did you rule from", expectedIntent: null },

  // childhood_environment (physical environment only)
  { text: "describe your early environment", expectedIntent: "childhood_environment" },
  { text: "what school did you go to", expectedIntent: null },
  { text: "who raised you", expectedIntent: null }, // emotional/relational → null
  { text: "what was your home like", expectedIntent: "childhood_environment" },
  { text: "did you have a happy childhood", expectedIntent: null },
  { text: "what was court life like for a child", expectedIntent: "childhood_environment" },
  { text: "were you spoiled as a kid", expectedIntent: null },
  { text: "what toys did you have", expectedIntent: null },
  { text: "who were your friends growing up", expectedIntent: null },
  { text: "what was the palace atmosphere like", expectedIntent: "childhood_environment" },

  // childhood_upbringing (training & instruction only)
  { text: "what training did you receive as a child", expectedIntent: "childhood_upbringing" },
  { text: "who was your teacher", expectedIntent: null },
  { text: "what subjects did you study", expectedIntent: null },
  { text: "how did princes learn back then", expectedIntent: "childhood_upbringing" },
  { text: "were you educated well", expectedIntent: null },
  { text: "what skills did you develop young", expectedIntent: "childhood_upbringing" },
  { text: "did your father teach you", expectedIntent: null },
  { text: "what lessons prepared you", expectedIntent: "childhood_upbringing" },
  { text: "were you a good student", expectedIntent: null },
  { text: "how did royal children train", expectedIntent: "childhood_upbringing" },

  // titles
  { text: "what was your official title", expectedIntent: "titles" },
  { text: "how powerful were you", expectedIntent: null },
  { text: "what authority did you have", expectedIntent: null },
  { text: "what honors did you receive", expectedIntent: "titles" },
  { text: "were you respected", expectedIntent: null },
  { text: "what position did you hold", expectedIntent: "titles" },
  { text: "how important were you", expectedIntent: null },
  { text: "what rank were you", expectedIntent: "titles" },
  { text: "were you the supreme ruler", expectedIntent: null },
  { text: "what did your crown represent", expectedIntent: null },

  // names_epithets (clear naming references)
  { text: "what epithets did you have", expectedIntent: "names_epithets" },
  { text: "why were you called great", expectedIntent: null },
  { text: "what does ramses mean", expectedIntent: null },
  { text: "how many names did you use", expectedIntent: "names_epithets" },
  { text: "what is your legacy name", expectedIntent: null },
  { text: "what did your cartouche say", expectedIntent: "names_epithets" },
  { text: "were you given a special name", expectedIntent: "names_epithets" },
  { text: "what do people call you today", expectedIntent: null },
  { text: "what is your famous name", expectedIntent: null },
  { text: "how should I address you", expectedIntent: null },

  // personality_traits
  { text: "what traits defined you", expectedIntent: "personality_traits" },
  { text: "were you a good person", expectedIntent: null },
  { text: "did people like you", expectedIntent: null },
  { text: "how did others see you", expectedIntent: "personality_traits" },
  { text: "were you feared or loved", expectedIntent: null },
  { text: "what made you special", expectedIntent: null },
  { text: "were you a wise leader", expectedIntent: "personality_traits" },
  { text: "did you care about your people", expectedIntent: null },
  { text: "what was your leadership style", expectedIntent: "personality_traits" },
  { text: "were you merciful or harsh", expectedIntent: null },

  // age_at_accession
  { text: "how old were you when you began ruling", expectedIntent: "age_at_accession" },
  { text: "who ruled before you", expectedIntent: null },
  { text: "how did you become pharaoh", expectedIntent: null },
  { text: "were you ready to rule", expectedIntent: null },
  { text: "did you inherit the throne young", expectedIntent: "age_at_accession" },
  { text: "what year did you become king", expectedIntent: null },
  { text: "were you the oldest son", expectedIntent: null },
  { text: "when did your reign start", expectedIntent: null },
  { text: "how long until you were pharaoh", expectedIntent: null },
  { text: "at what age did power come to you", expectedIntent: "age_at_accession" },

  // length_of_reign
  { text: "what was the length of your reign", expectedIntent: "length_of_reign" },
  { text: "when did your reign end", expectedIntent: null },
  { text: "what years did you rule", expectedIntent: null },
  { text: "was your reign long", expectedIntent: "length_of_reign" },
  { text: "did you rule for decades", expectedIntent: "length_of_reign" },
  { text: "when did you stop being pharaoh", expectedIntent: null },
  { text: "how successful was your reign", expectedIntent: null },
  { text: "were you pharaoh for a long time", expectedIntent: "length_of_reign" },
  { text: "what was your ruling period", expectedIntent: "length_of_reign" },
  { text: "how many decades on the throne", expectedIntent: "length_of_reign" },

  // daily_routine
  { text: "how did you spend your day", expectedIntent: "daily_routine" },
  { text: "what time did you wake up", expectedIntent: null },
  { text: "when did you eat meals", expectedIntent: null },
  { text: "what did you do in the morning", expectedIntent: null },
  { text: "how was your day structured", expectedIntent: "daily_routine" },
  { text: "did you have a busy schedule", expectedIntent: null },
  { text: "what filled your time", expectedIntent: "daily_routine" },
  { text: "when did you go to bed", expectedIntent: null },
  { text: "what occupied your days", expectedIntent: "daily_routine" },
  { text: "how did you organize your time", expectedIntent: "daily_routine" }
];


export const testDatasetErroneous = [
  { text: "what time is it", expectedIntent: null },
  { text: "tell me a joke", expectedIntent: null },
  { text: "how is the weather today", expectedIntent: null },
  { text: "can you recommend a movie", expectedIntent: null },
  { text: "i like pizza", expectedIntent: null },
  { text: "what is 2 plus 2", expectedIntent: null },
  { text: "do you like cats or dogs", expectedIntent: null },
  { text: "what is your favorite color", expectedIntent: null },
  { text: "can you dance", expectedIntent: null },
  { text: "sing me a song", expectedIntent: null },
  { text: "what is the capital of france", expectedIntent: null },
  { text: "how do i make pasta", expectedIntent: null },
  { text: "what is quantum physics", expectedIntent: null },
  { text: "tell me about modern technology", expectedIntent: null },
  { text: "what happened yesterday", expectedIntent: null },
  { text: "who won the world cup", expectedIntent: null },
  { text: "what is bitcoin", expectedIntent: null },
  { text: "how do airplanes fly", expectedIntent: null },
  { text: "what is the meaning of life", expectedIntent: null },
  { text: "can you help me with homework", expectedIntent: null },
  { text: "what should i eat for dinner", expectedIntent: null },
  { text: "how tall are mountains", expectedIntent: null },
  { text: "what is artificial intelligence", expectedIntent: null },
  { text: "do you speak spanish", expectedIntent: null },
  { text: "what is the stock market", expectedIntent: null },
  { text: "how do i lose weight", expectedIntent: null },
  { text: "what is love", expectedIntent: null },
  { text: "can you predict the future", expectedIntent: null },
  { text: "what is the best smartphone", expectedIntent: null },
  { text: "how do i learn programming", expectedIntent: null },
  { text: "what is democracy", expectedIntent: null },
  { text: "tell me about climate change", expectedIntent: null },
  { text: "what is the internet", expectedIntent: null },
  { text: "how do i make friends", expectedIntent: null },
  { text: "what is happiness", expectedIntent: null },
  { text: "can you read minds", expectedIntent: null },
  { text: "what is the universe made of", expectedIntent: null },
  { text: "how do i tie a tie", expectedIntent: null },
  { text: "what are the rules of chess", expectedIntent: null },
  { text: "can you drive a car", expectedIntent: null },
  { text: "what is the latest news", expectedIntent: null },
  { text: "how much does it cost", expectedIntent: null },
  { text: "where can i buy this", expectedIntent: null },
  { text: "what is your opinion on politics", expectedIntent: null },
  { text: "what is your address", expectedIntent: null },
  { text: "can you send me an email", expectedIntent: null },
  { text: "what is the speed of light", expectedIntent: null },
  { text: "how do plants grow", expectedIntent: null },
  { text: "what is the best restaurant nearby", expectedIntent: null },
  { text: "can you translate this", expectedIntent: null }
];
